version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-microservices
    environment:
      POSTGRES_USER: dduquejh
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-microservices
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
